name: Build and Publish
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '* * * * *' # Runs every minute every day
      branches:
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Publish
      run: |
        make
        mkdir -p bin
        mv HelloWorld.exe bin/
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: bin/HelloWorld.exe
