name: C++ Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Create binaries directory
      run: mkdir build

    - name: Build with GNU Make
      run: make

    - name: Move binaries to directory
      run: mv path/to/your/executables/* HelloWoeld.exe build/

    - name: Publish binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/
